### ISSUE TITLE
Support for dietary restrictions

### ISSUE THREAD

**Issue by LukasPietzschmann** [Tanikai/uniulm_mensa_api#1]
A good friend of mine (@Tim-h3) prefers vegan food, but is unable to know which of the offered courses is actually vegan. As the original pdf file provides this information, it would be awesome if your API would reflect that.

**Comment by Tanikai** [comment]
Has to be implemented in the [parser library](https://github.com/Tanikai/uniulm_mensaparser) dependency. Will update the API after that.

**Comment by LukasPietzschmann** [comment]
Awesome, thanks :)

**Comment by Tanikai** [comment]
Bumped parser library to newest version in commit https://github.com/Tanikai/uniulm_mensa_api/commit/571b58129a406f977ce95e874d3b133b963c24a5. Meals now contain the type (vegan, vegetarian, Beef, ...) and additional allergy information.
